### ISSUE TITLE
Cannot create an NSPersistentStoreCoordinator with a nil model

### ISSUE THREAD

**Issue by docterd** [piwik/piwik-sdk-ios#68] opened 2015-03-08 19:04 UTC
It still crashes with NSPersistentStoreCoordinate using the latest Cocoapod (3.1.1)

``` Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Cannot create an NSPersistentStoreCoordinator with a nil model'
*** First throw call stack:
(0x183b1259c 0x19425c0e4 0x1837b5378 0x10025860c 0x100258228 0x100256f78 0x100253618 0x10025351c 0x100253478 0x1849e6db8 0x183aca8d8 0x183aca588 0x183ac7fd4 0x1839f50a4 0x18cb8f5a4 0x188326aa4 0x1000a6aa4 0x1948caa08)
libc++abi.dylib: terminating with uncaught exception of type NSException```

**Comment by kevinkub** [comment] 2015-04-02 14:42
Same here. Did you find a solution?

**Comment by docterd** [comment] 2015-04-06 18:02
Unfortunately not.

**Comment by kevinkub** [comment] 2015-04-06 18:29
Thanks for your answer. I have come up with a solution, but as I am not an expert with frameworks yet, I do not know how good the solution is. 

To fix the problem I selected my main (not the pod) project and added the .xcdatamodeld to the "compile" section. Xcode asked me if I would like to add the file to my project and I confirmed. After that everything was running as expected. 

If you need any further hint let me know and I will add screenshots.

**Comment by mattiaslevin** [comment] 2015-05-23 06:35
It looks like CocoaPod is not including the xcdatamodeld from the pod when building your project. No CoreData model is generated and NSPersistentStoreCoordinator explodeds when the app is started.

I updated the podspec to follow the guidelines stated in this CocoaPods ticket
https://github.com/CocoaPods/Xcodeproj/issues/81
Hopefully this will solve the problem

If the problem continue can you please check:
1) After running `pod install`
2) There should be a folder under the Pod project named `PiwikTracker/Core/Resources` (or similar)
3) It should contain `piwiktracker.xcdatamodeld`
4) Go to your own target and Build Phases
5) There should be a `Copy Pods Resources`
6) If you build your target and go to the Report navigator (the right most option in your left panel) and select your last build
7) You should see something like `Run custom shell script Copy Pods Resources`
8) Expand and can see the xcdatamodeld being compiled into a momd

**Comment by mattiaslevin** [comment] 2015-05-23 06:35
Closing for now

**Comment by mattiaslevin** [comment] 2015-05-27 17:52
Reopening again.
Having issues with getting CocoaPods pick the correct version of the CoreData model.

Will need to investigate a bit more. Potentially I will just create a new schema (without versioning) and simply delete the the old database during the upgrade process. It will mean the buffered events will be saved but probably not the end of the world.

**Comment by mattiaslevin** [comment] 2015-05-29 21:10
Actually seem to work is you let Cocoapod download the version to git, but not if you pick it up from a local file system path.

Did a test project and verified that I can migrate from an older Piwik version to a new, the data model will be upgraded.

**Closed by mattiaslevin** 2015-05-29 21:10 UTC

**Comment by liuxue0905** [comment] 2016-06-22 07:34
5) There should be a Copy Pods Resources
There is any thing about piwik,I updated CocoaPods.What's the main point of view of "CocoaPods/Xcodeproj#81"?
