### ISSUE TITLE
iOS Media Analytics not working

### ISSUE THREAD

**Issue by ly0770** [piwik/piwik-sdk-ios#364] opened 2020-11-18 02:57 UTC
how to use the iOS SDK track Media Analytics, thanks~

**Comment by brototyp** [comment] 2020-12-13 14:31
Hi @ly0770, the SDK currently doesn't bring any custom functions to track Media Events. As a workaround you should be able to track custom events and use the `customTrackingParameters` to set the parameters you need.

Otherwise: I am open for a PR in this regard.

**Comment by brototyp** [comment] 2022-03-26 15:25
Since this ticket is pretty much a duplicate of #196 I am closing this one for now.

**Closed as completed by brototyp** 2022-03-26 15:25 UTC
Labels: enhancement
