### ISSUE TITLE
Device Model Name

### ISSUE THREAD

**Issue by goelay** [piwik/piwik-sdk-ios#347] opened 2020-09-11 08:51 UTC
Hello,
We are experience an issue where I am seeing seeing few model being reported as "Apple - iPhone" & "Apple - iPAD" instead of the device exact name.

**Comment by Guiboune** [comment] 2020-09-16 09:04
Same here

**Comment by brototyp** [comment] 2020-09-16 10:03
Hey, thanks for reporting. Do you have any details? Do you know if this any specific iOS version, or any specific devices where this happens?

**Comment by goelay** [comment] 2020-09-16 10:05
Hey,
It's not OS specific. We are not able to get info for specific device its occurring but its very easily replicable.

**Comment by brototyp** [comment] 2020-09-16 10:07
So it's only happening for a few specific devices? Do you know which devices?

**Comment by goelay** [comment] 2020-09-16 10:10
Its happening for majority of the devices I believe as per our analysis. We do not know the devices.
<img width="357" alt="Screenshot 2020-09-16 at 3 40 22 PM" src="https://user-images.githubusercontent.com/848659/93324009-f4f56e80-f832-11ea-831e-3d5ad0a08610.png">

**Comment by brototyp** [comment] 2020-09-16 10:11
Hm. That's interesting. Did that change appear along with an update of the SDK? Or maybe an update of the backend?

**Comment by goelay** [comment] 2020-09-16 10:13
We are on latest version and we are seeing this issue from a long time so it's not related to version I suppose.

**Comment by Findus23** [comment] 2020-09-16 10:28
It would be great if you could check the server access log for user agents (ideally of those unspecific visits). That way you can check on https://devicedetector.lw1.at/ how Matomo detects that specific user agent and maybe check if some information about the exact device is missing there.

**Comment by ghost** [comment] 2020-09-16 12:23
Hello, 

I guess the issue is from the devicedetector.lw1.at because even if I go to this url from iPhone 8, it says only iPhone as model property.

**Comment by Findus23** [comment] 2020-09-16 12:30
@BastienLebrun That's another issue: Apple does intentionally not mention the exact device type in the user agents anymore for privacy reasons when browsing in Safari, so there is nothing for Matomo to detect.

But that should not affect the iOS SDK as there the user agent can be built by the SDK code.

**Comment by brototyp** [comment] 2020-09-19 14:31
Hey @Findus23, thanks for your input here. I guess I know then why there are no device names visible. We (basically) use safari to generate the user agent. 

To solve this issue we would need to change this logic to either

1. generate our own user agent, or
2. send this kind of data via a different way than via the user agent.

Am I right, that there is no other way to send such information to the server other than the user agent? 
If we then have to generate the user agent by our selves, what is the required format for Matomo? What does Matomo parse? In why format does Matomo recognize devices? Is there some kind of documentation we could use?

**Comment by brototyp** [comment] 2020-09-19 14:58
Hey @BastienLebrun, @goelay and @Guiboune, thanks a lot for the followup. In theory, the SDK does modify the user agent, so that it contains the actual device identifier, such as `iPad3,6` instead of just `iPhone`. 

To figure out where exactly the problem is: Do you use the latest version (7.2.2) of Matomo? If that's the case, can you please check out the branch over [here](https://github.com/matomo-org/matomo-sdk-ios/pull/350), install it in your app and right after initializing the MatomoTracker add a `matomoTracker.logger = DefaultLogger(minLevel: .verbose)`? This should print something like `MatomoTracker [V] Generated User Agent: Mozilla/5.0 (x86_64; CPU iPhone OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 MatomoTracker SDK URLSessionDispatcher` in the console. If you run this on a device that is not recognized on the server, we can figure out what the generated user agent is, and maybe that helps to get closer to the issue.

**Comment by Findus23** [comment] 2020-09-19 15:55
@brototyp You are right that the only way to specify the device in Matomo is the user agent. It will be parsed by https://github.com/matomo-org/device-detector which gives the results users can see in Matomo.
For apple devices it uses the regex here:
https://github.com/matomo-org/device-detector/blob/c495cee660e1e8113fdea7929c659dd6943aae4d/regexes/device/mobiles.yml#L477

On https://devicedetector.lw1.at/ you can test the output of the latest version (master branch), so it might slightly differ from the one shipped in Matomo, but it shouldn't matter here.

Unfortunately user agents have no defined format as every device sends what they think is right. With iOS devices it is easier as they all have the same schema and contain the internal name of the device (maybe you can get the same name programmatically).

The user agent
```text
Mozilla/5.0 (x86_64; CPU iPhone OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 MatomoTracker SDK URLSessionDispatcher
```
contains no info about the device, so there is nothing that could be detected.


BTW: Do you know if you currently still send iOS user agents for iPads? Safari sends a macOS user agent by default to get websites to display desktop sites. (https://github.com/matomo-org/device-detector/issues/6313)

**Comment by brototyp** [comment] 2020-10-04 10:17
Thanks both of you for the feedback. 

I think we need to rethink our UserAgent generation. Right now the SDK asks the WebView to generate the UserAgent and will then replace `iPhone` with the actual iPhone version. There are just to many issues with it:

* WebKit as a dependency
* Asynchronous code: There is no synchronous way to let a WKWebView generate the UserAgent
* When the format of the UserAgent returned by WkWebView changes our code might break (I guess that's what is happening here)

I opened a [PR](https://github.com/matomo-org/matomo-sdk-ios/pull/353) that completely changes, how we generate the UserAgent. @BastienLebrun, @goelay and @Guiboune can you please have a look at it, to see if it works in your case?

**Comment by brototyp** [comment] 2020-10-25 11:29
The latest release, version 7.3, contains a major update un user agent generation that should fix this issue. 
I will close this ticket for now. Please feel free to comment here, if it doesn't.

**Closed as completed by brototyp** 2020-10-25 11:29 UTC
Labels: information needed
