### ISSUE TITLE
Make the visitorId usable from Objective-C

### ISSUE THREAD

**Issue by JiangWenjia** [piwik/piwik-sdk-ios#234] opened 2018-04-03 09:24 UTC
i use oc
so     visitorId need  @objc

**Comment by brototyp** [comment] 2018-04-06 12:48
Hi @JiangWenjia, thanks for the issue. Please check #235 if that fixes your problem.

**Comment by brototyp** [comment] 2018-04-06 12:58
Duplicate of #228.

**Closed as completed by brototyp** 2018-04-06 12:58 UTC
