### ISSUE TITLE
Crash KERN_INVALID_ACCESS

### ISSUE THREAD

**Issue by flaushi** [piwik/piwik-sdk-ios#209] opened 2017-12-07 06:59 UTC
Hi!
I hve just migrated to PIWIK and now I am seeing these crashes: http://crashes.to/s/b789c330938 and http://crashes.to/s/fdcc376e940

the corresponding code is:
```
+ (void) trackEvent:(NSString*)category andAction:(NSString*)action withLabel:(NSString*)label{
    [[[GAI sharedInstance] defaultTracker] send:[[GAIDictionaryBuilder createEventWithCategory:category action:action label:label value:nil] build]];
    NSLog(@"trackEvent %@ %@ %@",category,action,label);
    [[PiwikTracker shared] trackWithEventWithCategory:category action:action name:label number:nil url:nil];
}
```
and the initialization takes place here:
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    ...
    [PiwikTracker configureSharedInstanceWithSiteID:@"3" baseURL:[NSURL URLWithString:@"https://www.....com/internalpiwik/piwik.php"] userAgent:@"my-u-a-ios"];
```
Seems to be an issue with the memory queue.
Thanks in advance!
Olli

**Comment by brototyp** [comment] 2017-12-09 16:06
Hi @flaushi, thanks for your report. I think this is a duplicate of #203.

**Comment by flaushi** [comment] 2017-12-11 11:00
Can be, yes. To give some more information, here is an updated bug report [](http://crashes.to/s/b789c330938)

**Comment by brototyp** [comment] 2017-12-20 15:53
@flaushi Can you try out #216 and see if it fixes your issues?

**Comment by brototyp** [comment] 2018-01-04 10:18
Hi @flaushi, can you add some followup information here. Is this issue fixed by the #216 PR as well?

**Comment by flaushi** [comment] 2018-01-04 10:22
Yes, I am not receiving any bug reports related to piwik anymore.

**Comment by brototyp** [comment] 2018-01-04 10:24
Awesome. Thanks!

**Closed by brototyp** 2018-01-04 10:24 UTC
Labels: bug
