### ISSUE TITLE
User-Agent not submitted anymore

### ISSUE THREAD

**Issue by sebastianwr** [piwik/piwik-sdk-ios#67] opened 2015-03-06 09:41 UTC
Dear Piwik team,

I just tried the latest versions of the iOS SDK (both NSURL and AFNetworking version). Unfortunately, only the custom variables indicating device and OS give us any clue about how fragmented the app usage is.

The Device detector plugin of Piwik however relies on the User-Agent string that seems to have been submitted in earlier versions of Piwik but not anymore. It would be great if you could add this back into the project or explain shortly how it's possible to do so so that the DeviceDetector plugin works also for our mobile statistics.

Kind regards,
Sebastian

**Comment by sebastianwr** [comment] 2015-03-06 10:41
Ok nevermind, it was a typo in `PiwikTracker.h` ... you might wanna release a new minor version, this was quite frustrating. ;)

**Comment by mattiaslevin** [comment] 2015-05-22 20:29
I know this is a bit old, but I am trying to close out some bugs.
Can you please give me some more details about the where the typo is?
Thanks

**Comment by tarbrain** [comment] 2015-05-22 21:45
That's a duplicate of #62 and #65

**Comment by mattiaslevin** [comment] 2015-05-23 08:55
Great, then this should be fixed.
Closing.

**Closed by mattiaslevin** 2015-05-23 08:55 UTC
