### ISSUE TITLE
Crash with 4.3.0 version

### ISSUE THREAD

**Issue by luohui8891** [piwik/piwik-sdk-ios#203] opened 2017-11-23 09:42 UTC
Hi guys,

I upgrade `piwik-sdk-ios` to 4.3.0 in our new version and public to external beta testing.
But I got two new kinds of crash reports from beta users.
Here is the [crash 1](http://crashes.to/s/cbe3675bb4c) and [crash 2](http://crashes.to/s/bd83b468720)
Looks like it occurred when the SDK dispatch to send request.

Any idea?

BTW, I will upgrade sdk to 4.4.0 in the new beta build.

**Comment by brototyp** [comment] 2017-11-27 19:33
Hi @luohui8891, thanks for the bug report. I will investigate and will get back with you.

**Comment by luohui8891** [comment] 2017-11-29 03:31
@brototyp here is a [new one](http://crashes.to/s/e1ebe3027d0) in 4.4.0.
I think they are same issue about `Event` memory management.

**Comment by luohui8891** [comment] 2017-11-30 07:04
Any update?

**Comment by brototyp** [comment] 2017-12-01 08:41
Hi @luohui8891, badly no. I haven't had any spare time. I will find some on the weekend.

**Comment by brototyp** [comment] 2017-12-03 10:10
Hi @luohui8891, I just noticed you are using the 4.3.0, while the 4.4.0 is available. In 4.4.0 we fixed some issues with the SessionDispatcher. Do you think it is possible to update to 4.4.0?

Additionaly: Is there a log (possibly of just the Piwik lines)?

**Comment by luohui8891** [comment] 2017-12-04 02:18
```
- (void)trackForum:(TKForumManager*)forumManager screen:(NSString *)screen{
    NSString * piwikID = forumManager.ForumConfigModel.sitePiwikID;
    if (piwikID.length == 0 || [piwikID isEqualToString:@"0"]) {
        return;
    }
    TKPiwikTracker * tracker = [self trackerForPiwikID:piwikID];
    if (tracker) {
        // Here is Line 49
        [tracker trackScreenWithScreen:screen url:[NSURL URLWithString:forumManager.ForumURL]];
    } else {
        dispatch_async(dispatch_get_main_queue(), ^{
            TKPiwikTracker * tracker = [[TKPiwikTracker alloc] initWithPiwikID:piwikID];
            [tracker trackScreenWithScreen:screen url:[NSURL URLWithString:forumManager.ForumURL]];
            self.cache[piwikID] = tracker;
        });
    }
}
```

**Comment by brototyp** [comment] 2017-12-09 16:08
Hi @luohui8891, I am still struggling to reproduce this issue. I am suspecting this issue only appears when called from Objective-c or in a mixed environment. I will digg further into that.

**Comment by luohui8891** [comment] 2017-12-12 06:42
Thanks. 
I downgrade the SDK to my forked repo based on 4.0.0 in our Application.
Tell me if you got any fix, I will help you to confirm in our beta build.

**Comment by flaushi** [comment] 2017-12-15 06:55
Yes, I am calling from Objective-C and do encounter this error too!

**Comment by luohui8891** [comment] 2017-12-18 04:06
Hi @brototyp by reviewing code, I think this issue is caused by the `MemoryQueue`.
It is not thread-safe. 
Should we add some protection?

**Comment by brototyp** [comment] 2017-12-18 17:34
Hi @luohui8891, thanks for that Idea. My initial reaction was "That can't be, we are moving all the calls to the main thread." but actually that is not right. All (indirect) calls to `internal func queue(event: Event) {` that are sent in the background will use the `MemoryQueue` from the background. I will digg into that tonight and see weather we should make the `MemoryQueue` thread save or move all calls to it to the main thread.

**Comment by flaushi** [comment] 2017-12-21 12:58
The problem is that I cannot force the crash, means I have to ship a new version to all users to see an effect. 

I have integrated your PR now temporally, and not crashes happen on my debug devices.

I am not happy with releasing an app version with non-release versions of libraries.

**Comment by flaushi** [comment] 2017-12-22 10:42
I am submitting a new version that includes this bugfix to the store now. I'll report on the effect. Thanks @brototyp ! Merry xmas

**Comment by luohui8891** [comment] 2017-12-25 02:32
@brototyp because of the crash issue, we still using the Piwik SDK from on my forking repo.
Last week, we did a [fix](https://github.com/luohui8891/piwik-sdk-ios/commit/9227e195ee62b3366d182e3e72533d53589a0118) and released it in a new version.
How we have released 20% of this version and didn't see the crash anymore.
I think the fix is better then `we are moving all the calls to the main thread.`, but still not the best.
We can submit a PR of this fix to you if you'd like.

**Comment by brototyp** [comment] 2017-12-31 16:08
Hi @flaushi, thanks for the followup! Let's hope it fixes the issue. 
Hi @luohui8891, I started with a similar implementation but changed it because synchronizing it in a certain thread might lead to issues, if multiple threads would use the queue. For example: Thread 1 gehts 20 Events, Thread 2 gets 20 Events, both dispatch those Events, both remove these Events. Those issues aren't solved in my solution, but they don't seem to be fixed in the MemoryQueue. The PiwikTracker makes sure those can never happen. What do you think?

**Comment by flaushi** [comment] 2018-01-02 10:28
So, after 10 days, I can confirm that the crashes **do not happen** anymore. Thanks!

**Comment by brototyp** [comment] 2018-01-04 10:17
Awesome. Thanks for the followup! I will merge the PR and close this issue. Thanks for your help @flaushi and @luohui8891!

**Closed by brototyp** 2018-01-04 10:17 UTC
Labels: bug
